name: KE-complex_modifications CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: recursive
      - name: rebuild
        run: make rebuild
      - name: check uncommitted changes
        run: bash core/scripts/check-uncommitted-changes.sh
      - name: tests
        run: make -C tests
